
      # The name of this app. Must be unique within a project.
name: app

# The runtime the application uses. The 'type' key defines the base container
# image that will be used to run the application. There is a separate base
# container image for each primary language for the application,
# in multiple versions. Check the PHP documentation
# (https://docs.platform.sh/languages/php.html#supported-versions)
# to find the supported versions for the 'php' type.
type: 'php:8.1'

dependencies:
    php:
        composer/composer: '^2'

# The following block defines a single writable directory, 'web/uploads'
# The 'source' specifies where the writable mount is. The 'local' source
# indicates that the mount point will point to a local directory on the
# application container. The 'source_path' specifies the subdirectory
# from within the source that the mount should point at. 

relationships:
    database: "db:mysql"


    

# The size of the persistent disk of the application (in MB).
disk: 3000

access:
    ssh: admin

mounts:
    'web/files':
        source: local
        source_path: 'web-files'
    'var/cache':
        source: local
        source_path: cache
    'var/log':
        source: local
        source_path: log
    # [PE Cluster] For cluster it's recommended to rather use a performant shared session storage like Redis/Memcached.
    'var/sessions':
        source: local
        source_path: sessions
    'var/encore':
        source: local
        source_path: encore
    'public/var':
        source: local
        source_path: var
 ##   'public/images/properties':
  #      source: local
  #      source_path: images/properties
  
    'public/media':
        source: local
        source_path: media
    'public/images/properties':
        source: local
        source_path: images/properties
    'public/images/Post':
        source: local
        source_path: images/Post
    
        

#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form '<service name>:<endpoint name>'.



hooks:
    build: |
        set -e
    deploy: |
        set -e
 
#        bin/console assets:install --symlink --relative public
#        bin/console cache:clear
#        bin/console doctrine:database:drop --force
#        bin/console doctrine:database:create
#        bin/console doctrine:schema:create --no-interaction
#        bin/console doctrine:fixtures:load --no-interaction

web:
    locations:
        '/':
            root: 'public'
            passthru: '/index.php'
            index:
                - index.php
            # No caching for static files.
            # (Dynamic pages use whatever cache headers are generated by the program.)
            expires: -1
            scripts: true
            allow: true
            rules:
                # Disallow .mp4 files specifically.
                \.mp4$:
                    allow: false
                    expires: -1
        # Set a 5 min expiration time for static files here; a missing URL
        # will passthru to the '/' location above and hit the application
        # front-controller.
        '/images':
            passthru: true
            allow: false
            rules:
                # Only allow static image files from the images directory.
                '\.(jpe?g|png|gif|svgz?|ico|bmp)$':
                    allow: true
        '/media':
            expires: 300
            passthru: true
            allow: true
            rules:
                # Only allow static image files from the images directory.
                '\.(jpg|png|gif|svgz?|ico|bmp)$':
                    allow: true
